language: cpp

services:
  - docker

cache:
  directories:
    - "/home/travis/vcpkg"

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        hosts: https.testserver.lan
        apt:
          packages:
            - g++-4.8
            - curl
            - wget
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

before_install:
  - WORK_DIR="$(pwd)"

install:
  - ./ci/update-or-install-vcpkg.sh "${WORK_DIR}"

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - cd "${WORK_DIR}"/ci
  - ./gen-certs.sh
  - python3 render-certs-header.py
  - cd "${WORK_DIR}"
  - mkdir build-travis
  - cd build-travis
  - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake
  - make
  - docker run -d -p="8443:8443" -v="${WORK_DIR}:/home/restful" --entrypoint="/home/restful/build-travis/restful" centos:7 0.0.0.0 8443 /home/restful/
  - cd "${WORK_DIR}"/ci
  - python3 test-server.py https.testserver.lan -p 8443
  - docker kill $(docker ps -q)

notifications:
  slack:
    secure: DyC2E6wBNP+xgiXaU5shidrZTPNCZw1v6w1ga9esORojZsgPmvC1D1CRn26DsgOlHhHgcc42YWXpdjVJLQ2HdZ9eVEraaR5Hap0x4AHJv3sDMf6yy5Jrmd62hOnpy6lMq15ntdEMqF3SJGZxAVa5wSRCnExvH95a9ATGlCawPuoNuZ5WQuE25bmZJagkWsQXbjtBOm5VEn5J06IhTsrCkb3/hCL+zAQVTM+KFnScfq8VZ+ZtRdY9nQ+lqMaG/k0cFvtPHHfUNqETuT4A8Ub5bHnVCmzBYZTPCwCTt7srirx+GvdmeRxZkv58wAhxm0N2E9MCq6Rxf+avFFXMZEZG0mjpa6MXkGfwWSlGx5Ms+KM5b3QgpfXgPzdLKXrrOGum0v7KVKlVUMipVW3vCDNTHBC1yfIn8X9etF7pCgMUURKEesFj0VzJ9oJcdVnP/+KjzTOSemk7UMoRbZgbpgCCf82Oy1ys5krXv9sDYKG1F2RhBQnblpUcG+GNzbzoKBuCE0BiERyHI4NRz1yH1kRWuNjRqhie7IjHMKBKl5n6nm8wBXyPx/3FtzhqopV7HQFV/tgad7sgRatscZnVZBI0NmmsRGxU7CPDucd4MJB9ARSuyJvZOrTVwR0FKxc0EdOffwrmL2mqTJjwV6HscaTxgjZpEZwerJNVFkZPrObiFHo=
  email: false
