language: cpp

cache:
  directories:
    - /home/travis/vcpkg

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        hosts: https.testserver.lan
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - curl
            - wget
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

before_install:
  - WORK_DIR="$(pwd)"

install:
  - ./ci/update-or-install-vcpkg.sh "${WORK_DIR}"

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - cd "${WORK_DIR}"
  - mkdir build-travis
  - cd build-travis
  - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake
  - make
  - ./restful 127.0.0.1 8443 .. &
  - ./../ci/test-server.sh
  - kill %1

notifications:
  slack:
    secure: MSZB2wEMSbXrFUu6OmlD38MZmHDO5eW33SLBGU45QL123wfy2jEA5ZbGNoTyv8u+nBmP/dSjlEjXQ6QrCsBlSFpsdwzSwuEVn5Naq3f4uNmD1N0cZu8MDaU0UIuRz58ODJfUcMG/422QbjUEhRjCBlX7XMNGgb89y+XQfvcxqi/vwu3NSWz7hZFTswR70453S38HvznoCQiZfZm1s4OJ7zpsBzhLqI8Qe7MjvSAOlQ9e3Td6G69qSMby0NoQlFJzW3J7OAiIU0+HJ7CQdZg7Qczcj5L/NqQ6lXsgXXt8OB+A8yUa4UuBOgg5X7/ILVUhBgEVlavvG8NW8IocHWZ2+Dg6taC2LYHI70KQybRWB2X10VJ/d5n0svLWfcCTllQ9irrVnE+i49xzooarajsO3MPXuE0nGXsfgTsPwtT6OxYd68jLPIlsBM0SDQQPZa6H8LBIOKHZMNPwjDIE3jJ/40e4j/pU13juH267O2tgGAyRQFAeq54INUKUvlJUNxzRRt8KLMcnm2ctUlrNvBkkzgX86TlVU7W+EttRKEnbA2OgUCzvIaIe1hEIFzNjged5Gxi6zgivSIAz2QwEP9n0jswMokaI5DAX+Doe6JZPSXQ/CnAzu+LkdS6NYq8PUA+QgBKG87W1XILvy5EqhZtvbMahBhvchYpXCPf7FZtAFCE=
  email: false
